CREATE TABLE Categories (
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(50)
);

CREATE TABLE Items (
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(255),
Price FLOAT,
Description NVARCHAR(1000),
IdCategory INT FOREIGN KEY REFERENCES Categories(Id)
);
